backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads" # Where uploaded files are stored
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "books"
    label: "Books"
    folder: "_books"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "PDF File", name: "file", widget: "file" }
